apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  pg_database_url: "my-config-value"
  redis_host: "localhost"
  redis_port: "6379"

---

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  pg_database_user: <base64-encoded-secret-value>
  pg_database_pswd: <base64-encoded-secret-value>
  #redis_pswd: <base64-encoded-secret-value>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      containers:
        - name: my-java-app-container
          image: 2207sawan/java17-springboot-redis-postgres:latest
          ports:
            - containerPort: 8080
          env:
            - name: MY_CONFIG_VARIABLE
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: redis_host
            - name: MY_CONFIG_VARIABLE
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: redis_port
            - name: MY_CONFIG_VARIABLE
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: pg_database_url
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: pg_database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: pg_database_pswd
            # - name: REDIS_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: my-secret
            #       key: pg_redis_pswd      
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: my-java-app-service
spec:
  selector:
    app: my-java-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
